### PR TITLE
Add alt_g

### PR DESCRIPTION
**Pull request by kirbyfan64**
See #122. I just went ahead and implemented it, since there was no response from @xcombelle.

### CODE REVIEW

**Comment by nilnor** [comment]
I made some comments for #122 regarding the implementation, which still apply.

**Comment by kirbyfan64** [comment]
@nilnor Fixed.

**Comment by nilnor** [comment]
All right, looks good! One question though, should we a working binding for OS X, since `alt` won't work there?

**Comment by nilnor** [comment]
Well, `ctrl_g` is still taken (`buffer-grep`), so perhaps `ctrl_shift_g`?

**Comment by kirbyfan64** [comment]
@nilnor Wait, shouldn't `buffer-grep` be `command_g` on a Mac, since that's the "primary key"?

**Comment by nilnor** [comment]
Right you are (and it is), so that does free up `ctrl_g` for OS X. I can't say I know whether it's suitable or not, but it works for me. @shalabhc, any preferences?

**Comment by shalabhc** [comment]
My preference agrees - `ctrl_g` for `goto-line` and `command_g` for `buffer-grep` sounds good.

**Comment by kirbyfan64** [comment]
@howl-editor/developers How's this?

**Comment by nilnor** [comment]
That's a wrap :)

**Pull request merged**
