### PR TITLE
Blueberry blend theme

### PR DESCRIPTION
**Pull request by shalabhc**
I'm happy with how this looks now, but also open to further suggestions.

### CODE REVIEW

**Comment by nilnor** [comment]
Great :+1: 

Let's have this in 0.4 since it does not affect anything else.

**Comment by shalabhc** [comment]
Yay!

So - should we generate a new website then?

**Comment by nilnor** [comment]
Yes, sounds like a good idea! You want to do that, and generate the screenshots?

**Comment by shalabhc** [comment]
Yes, on it...

**Comment by shalabhc** [comment]
Done - pushed commits and updated website for new theme.

**Pull request merged**
