### PR TITLE
Even *more* lexer fixes!!

### PR DESCRIPTION
**Pull request by kirbyfan64**

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Funny thing: THE FREAKING C BUNDLE DOESN'T WORK FOR ME! You fixed the issue with lexing C comments (#66), but it still won't work for me. In fact, *nothing* I change in the C/C++ lexer works. I `rm -rf`'d `/usr/local/share/howl` twice in a row and reinstalled from scratch, as well as deleting all the bytecode files in the Howl source directory. Nothing works. :/

**Comment by kirbyfan64** [comment]
I also updated the CS lexer again with proper type definition lexing and ES6 generators.

**Comment by nilnor** [comment]
@kirbyfan64 You're going to have to be more specific. What is it that doesn't work? You changing the lexer or what?

**Comment by kirbyfan64** [comment]
@nilnor Sorry. That really doesn't have anything to do with this PR. Basically, no changes made to the C lexer have an effect. I can wipe the whole Howl source directory, delete `/usr/local/lib/howl`, etc., but the changes made still won't appear.

I've been meaning to try and get the cool `type_def` highlighting working in the C lexer, but nothing I do has an effect. At all. :(

Anyway, like I said before, that's completely unrelated to this PR. Sorry. :)

**Comment by shalabhc** [comment]
@kirbyfan64 - did you make sure there is no C bundle in ~/.howl/bundles?

**Comment by kirbyfan64** [comment]
@shalabhc Grrr... Unfortunately, no. :(

Anyway...back to topic...how's the PR looking? :)

**Comment by kirbyfan64** [comment]
I also fixed some Nim indentation issues.

**Comment by nilnor** [comment]
Looks good!

Let's see if we can provide some assistance with your other issue over email.

**Pull request merged**
