### PR TITLE
Timers

### PR DESCRIPTION
**Pull request by nilnor**
This adds primarily:

- An `.idle` property for Application, returning the time in seconds Howl has been idle
- A new signal `idle`, fired when Howl has been idle for a configurable amount of time (currently defaults to 60s)
- A new signal `every-second`, fired once every second

This in itself is not particularly super exciting perhaps, but it enables the addition of other features that runs upon idle. Things I'm not sure about: 

- Do we want the `every-second` signal? I see that it could be useful for easily running periodical tasks, but that might be forward engineering. It does not cost much though since we have it anyway for the idle timer.
- A good default for the idle timeout. Currently 60s, but that could be considered too short

### CODE REVIEW

**Comment by kirbyfan64** [comment]
One potential cause of worry with `every-second` would be the fact that, if the callback is even a little bit slow-ish, it will be brutally obvious...

**Comment by shalabhc** [comment]
Very nice!

Funnily, I thought 60s for idle is too long :) Do you have any specific application for this?

What constitutes idle perhaps depends on context? Another possible API might be something like `timer.when_idle 60, do_something` which can subsume both signals.

**Comment by nilnor** [comment]
@kirbyfan64 Yes, a badly written handler could definitely make things laggy, but then that's already true for the existing timer functions as well, as well as for many of the other signals that are fired. We control what goes into the core, and a user will have to control their own custom code.

**Comment by nilnor** [comment]
@shalabhc That's the API I first thought about. The reason for not going with that was that then I would have to write yet another little custom dispatcher in the timer module, whereas just using a signal means everything is taken care of already. I also toyed with the idea of having `short-idle` and `idle` signals, but that didn't end up feeling good. Anyway, I do find it useful to be able to schedule tasks on shorter idle periods, so I will perhaps revisit this.

e1be9d5073a8576123e7c72bd02275c19c3f3b44 in the janitor branch contains a first example use of this, a new module for doing house-keeping on idle (closing old buffers, releasing memory).

**Comment by nilnor** [comment]
So, I rewrote it to provide an `on_idle` instead. I removed both the previous signals, as I concluded that I didn't like the `every-second` signal after all.

**Comment by nilnor** [comment]
Also, janitor example is now at f29b0f9eea0d2601870de076d316956fa6ff85c0 after the changes.

**Comment by shalabhc** [comment]
Yup I definitely like the new API more.

**Pull request merged**
