### PR TITLE
Bind window-toggle-fullscreen to F11 (instead of Alt-F11) and Alt-Enter.

### PR DESCRIPTION
**Pull request by mfxmfx**

### CODE REVIEW

**Comment by mfxmfx** [comment]
Minor cleanup and rebased on current master.

**Comment by kirbyfan64** [comment]
Why alt+enter, too? Seems like an obscure fullscreen key combo...

**Comment by mfxmfx** [comment]
Alt-Enter is a common shortcut for us "old timers" (it orginates from command.com and cmd.exe terminals under Windows) - please see the git commit message for more info.

**Comment by nilnor** [comment]
I recognize Alt-Enter as well from way back, but that was a long time ago now and as per the comment I'd say it's not widely recognized today. So, I think just having F11 by default is better - those wanting Alt-Enter can easily bind it themselves.

**Comment by mfxmfx** [comment]
Updated and rebased to current master.

**Comment by nilnor** [comment]
:clinking_glasses:

**Pull request merged**
