### PR TITLE
Make File.with_tmpfile() return the callback result.

### PR DESCRIPTION
**Pull request by Janfel**
`File.with_tmpfile()` now returns the return values of the passed callback, if successful, instead of an unhelpful `nil`.

### CODE REVIEW

**Comment by nilnor** [comment]
Seems like a good change as intended. The logic is actually inverted though, which probably explains all the spec errors from travis since this now raises an error for every successful call. You can read a little bit about how to run the specs [here](https://howl.io/doc/manual/dev-howl.html)

**Comment by nilnor** [comment]
Oh, and if we could add a short spec for the new behaviour as well then :+1: .

**Comment by Janfel** [comment]
I feel so stupid right now... thanks for writing all those specs.
I have fixed it and added a spec for the new behaviour.

**Comment by nilnor** [comment]
No worries. Looks good now, thanks!

**Pull request merged**
