### PR TITLE
Bind select-all to ctrl_a instead of ctrl_shift_a in default keymap.

### PR DESCRIPTION
**Pull request by mfxmfx**

### CODE REVIEW

**Comment by shalabhc** [comment]
+1 because this is the more common shortcut for select all, IME.

But can we also change the mac shortcut to meta_a (see https://support.apple.com/en-us/HT201236)

**Comment by nilnor** [comment]
Let's get the OSX change in as well and then we can merge this.

**Comment by mfxmfx** [comment]
Updated for OSX and rebased on current master.

**Comment by nilnor** [comment]
:+1:

**Pull request merged**
