### PR TITLE
Add a basic mode for Cabal files (Haskell)

### LINKED ISSUE #556: A basic mode for Cabal files (Haskell)
I've created a basic mode to provide syntax highlighting for Cabal build files. It's useful to anyone writing Haskell in Howl.

I'll send a PR shortly.

### PR DESCRIPTION
**Pull request by dgaw**
Closes #556

### CODE REVIEW

**Comment by refi64** [comment]
Thanks for the contribution! However, basic_modes are generally "legacy" lexers (pulled from LPeg I think?). All the new ones are Howl-native bundles instead.

**Comment by dgaw** [comment]
Thanks for reviewing @refi64!

If this is a matter of packaging then I can create a new bundle called "haskell" and move the haskell mode along with my cabal mode from "basic_modes" into this bundle.

What do you think?

**Comment by refi64** [comment]
I mean you *could*, but they have slightly different syntaxes, even though they're both built on top of LPeg, so it would have to be more of a port. For the moment, I'd suggest just moving the Cabal one over to make things easier.

**Comment by dgaw** [comment]
I use Haskell often so I don't mind spending a little time porting the Cabal mode, as well as the Haskell mode to the new syntax. 

I think it would be a logical move to create a "haskell" bundle with those two modes in it since all Haskell projects use Cabal files. Also this would give us a container for future development of Haskell-related functionality.

@refi64 Thanks for reviewing my PR. It took me a while to get back to this, sorry! Do you see any problems with this?

**Comment by shalabhc** [comment]
@dgaw, given the code is small, do you mind porting it to the 'new style' modes in its own bundle? E.g. `bundles/cabal`.

For a simple example you could look at bundles/haml.

**Comment by dgaw** [comment]
I don't mind porting the `cabal` mode in its own bundle.

However, what do you think about creating a `haskell` bundle I [mentioned earlier](https://github.com/howl-editor/howl/pull/557#issuecomment-612810470)?

**Comment by shalabhc** [comment]
Oh ya - a haskell bundle sounds even better.

If you do, please add an examples folder like some bundles have with a file containing haskell code. Doesn't have to work, just to see the syntax highlighting.

**Comment by dgaw** [comment]
Sure. I'll add an examples folder when I get around to implementing this.

**Comment by dgaw** [comment]
Superseded by #584

**Pull request closed without merging**
