### PR TITLE
Proper OS X keymap

### PR DESCRIPTION
**Pull request by hvze**
Rebound some keys to work on OS X.

### CODE REVIEW

**Comment by shalabhc** [comment]
:+1: 

Some comments might only make sense in the context of this diff so they could probably be adjusted. In general I like all changes I see there (even though I haven't actually tried them out).

**Comment by hvze** [comment]
Yeah, I'm going to do some more testing with keys and see if I can increase efficiency.

**Comment by shalabhc** [comment]
@hvze - are you happy with this keymap now?

**Comment by hvze** [comment]
I'm gonna find my laptop and do some more modifications, I've been using it for a while but I will make the longer keybinds feel more comfortable.

**Pull request closed without merging**
