### PR TITLE
Monokai theme

### PR DESCRIPTION
**Pull request by barnybug**
Replacement PR for #165 based off master.

### CODE REVIEW

**Comment by shalabhc** [comment]
If I merge this into the current master, the monokai theme doesn't quite look right. I also see this error when I try and switch to 'monokai':

Error invoking listener for change (gutter_styling: table: 0x40c3dc18 -> table: 0x415c3568): ../lib/aullar/gutter.moon:21: bad argument #1 to 'pairs' (table expected, got string)

**Comment by barnybug** [comment]
That's odd, works fine for me. That error was the same I saw prior to updating the gutter background part (as in the old branch).

**Comment by shalabhc** [comment]
Sorry false alarm - was trying out the 'monokai-theme' branch instead of this one :confused: 

Works great!

**Comment by nilnor** [comment]
Great work, thanks!

**Pull request merged**
