### PR TITLE
Monokai theme

### PR DESCRIPTION
**Pull request by barnybug**
First off - thanks for this great text editor!
I've created the ubiquitous Monokai theme for howl.

### CODE REVIEW

**Comment by shalabhc** [comment]
Thank you - it's beautiful!

BTW, you probably want to look at the `ui-rework` branch as well since themes will need readjustment once that is merged.

**Comment by barnybug** [comment]
Cool - happy to wait and rebase if that merges first.

**Comment by nilnor** [comment]
Great! Yes, it would be nice to get #157 in first. The plan was to more themes in first, but I will try to finish the first one and then we can get this in on top of the new structure. One question though, the popups are still dark blue, intended or a remnant of the Midnight Blue theme?

**Comment by shalabhc** [comment]
I believe you mean the documentation pop-ups (`ctrl_q`, screenshot below), since auto-complete pop-ups look ok?

monokai-doc-popup

**Comment by nilnor** [comment]
@shalabhc well really all popups, completion popups look that way to me as well.

**Comment by shalabhc** [comment]
Weird. Completion popups look different for me:

monokai-popup

**Comment by nilnor** [comment]
Closing this as it's superseded by #165.

**Pull request closed without merging**
