### PR TITLE
Make 'buffer-modified' signals for undo/redo work as advertised.

### PR DESCRIPTION
**Pull request by mfxmfx**

### CODE REVIEW

**Comment by nilnor** [comment]
Looks good, but the new return values for the `undo`/`redo` methods could also be speced at the same time (in aullar).

**Comment by mfxmfx** [comment]
I will provide an updated version with a spec test, but I need to know if you are willing to merge this first.

**Comment by nilnor** [comment]
Sure, I like the changes, so I'll be happy to merge an updated version.

**Comment by mfxmfx** [comment]
Obsolete - in the meantime if rewritten aullar to proper suport vi-mode undo/redo cursor movement, so closing this.

**Pull request closed without merging**
