### PR TITLE
Add additional Scheme source extensions

### PR DESCRIPTION
**Pull request by stutonk**
The following extensions are included:
	.sld -- R7RS Library Source
	.sls -- R6RS Library Source
	.ss  -- 'Scheme Source' as used in some implementations (e.g. Chez)

### CODE REVIEW

**Comment by nilnor** [comment]
While I wouldn't mind adding these extra extensions, I'm interested to hear whether we could instead use the newer `lisp` mode instead? That's a newer, custom, Howl mode for lisp languages that I've written some time ago, which should have better indentation support, etc. Do you think you could try that out for scheme and see whether that works as well or better? Simply uncomment the entire scheme definitions block from the basic modes and add the extensions to the lisp mode instead (bundles/lisp).

**Comment by stutonk** [comment]
Sure; I'll give it a shot and let you know how it goes.

**Comment by stutonk** [comment]
After using it for a few days I don't notice any problems with editing Scheme code in Lisp mode. Indentation is MUCH better than having to fiddle manually. If it's not 100% accurate to the canonical indentation algorithm, it definitely appears to be close enough. The lexer it uses seems to get all the major stuff for Scheme as well. I'd recommend your proposed change over the one I proposed here.

**Comment by nilnor** [comment]
Thanks for the feedback! I've now switched things over in master.

Indentation for lisp is hard (more likely impossible) to get right for all languages. I wrote this mode with Clojure in mind originally, and as I recall the canonical indentation there was dependent not only on syntax but differed depending on what exactly the first form element was. Anyway, to make this better it would be possible to define a custom `scheme` mode that derives from the lisp mode. Indentation support could then be tailored exactly towards scheme.

**Pull request closed without merging**
