### PR TITLE
Pony syntax support

### PR DESCRIPTION
**Pull request by equim**
Adds basic syntax support for Pony language.

### CODE REVIEW

**Comment by MarcusE1W** [comment]
Funny, I have just added one in the Wiki as a bundle. Yours looks more complete I have to say.

**Comment by kirbyfan64** [comment]
I don't believe there's anything in Howl to support snippets yet. 

`buffer-structure` is handled by mode.moon. You can see the Python mode for an example.

**Comment by nilnor** [comment]
I won't add any new basic modes to Howl, all new language support should be added using the native Howl lexing instead and as bundles. The basic mode support is just for old TextAdept lexers. The Howl lexing is way more powerful, and allows sub-lexing, etc. There's a lack of documentation unfortunately, but have a look at one of the native Howl language bundles for inspiration (one point in particular, all new languages bundles in the core should be accompanied by a comprehensive "misc/example.EXT" illustrating the support syntax.

**Comment by MarcusE1W** [comment]
As mentioned, there is a Howl style pony lexer [here](https://gitlab.com/MarcusE1W/howl-pony) that needs more polishing. Looking at @equim 's pony lexer I noticed some gaps already. This Howl lexer is also linked in the Wiki.

Hopefully support for `buffer-structure` can also be added. I will have a look at the Python lexer.

@kirbyfan64  Regarding the snippets (called code blocks in the docu) I had found this [info](https://howl.io/doc/manual/editing.html#code-blocks)  in the docu with an example for Lua and was wondering how to create that.

I can write a how-to how to write a simple! lexer for Howl and link it in the Wiki, if this is ok? .  I am not very familiar with P lexer though.

**Comment by MarcusE1W** [comment]
As mentioned, I have created a Howl lexer [here](https://gitlab.com/MarcusE1W/howl-pony)
It needs a bit more polishing, I noticed already some missing bits by looking at @equim 's lexer.

The tip for the `buffer-structure` worked very well, I have added some structure to the pony lexer.

@kirbyfan64 I have found [this](https://howl.io/doc/manual/editing.html#code-blocks) part of the docu for snippets/code-blocks  and wondered how to create that myself.

**Comment by equim** [comment]
Thanks all.

I made this as a basic mode thinking that might be an easy way to add support to 3 different editors at once (scite, textadept and of course howl) but I did have a sneaking suspicion it might be rejected.

I'll have a look at yours, @MarcusE1W.

Should that bundle ultimately be raised as a pull request or is it better to keep it separate?

**Comment by MarcusE1W** [comment]
@equim  I have merged your PR for the Wiki bundle.

**Comment by nilnor** [comment]
@equim @MarcusE1W The pony bundle could be maintained separately, but if there's enough demand for it I would also be open to include it in the core. At any rate this PR as is will not be merged, so let me know what should be done, or otherwise I'll close this for now.

**Comment by MarcusE1W** [comment]
I guess if @equim agrees then this PR could be closed as Pony is supported by a bundel now.
Linked in the Wiki.

**Comment by equim** [comment]
Yep, I've closed this now since we have a bundle linked from the wiki.  Thanks all.

**Pull request closed without merging**
